# Generated by Django 4.0.6 on 2022-07-18 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nova_competicao', '0002_alter_competicao_local_da_competicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competicao',
            name='nome_da_competicao',
        ),
    ]
