# Generated by Django 4.0.6 on 2022-07-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_competicao', models.CharField(max_length=200)),
                ('modalidade', models.CharField(choices=[('1', '100 Metros'), ('2', 'Lançamento de Dardo')], max_length=1)),
                ('local_da_competicao', models.CharField(max_length=100)),
                ('data_e_hora', models.DateTimeField(auto_now_add=True)),
                ('nome_do_atleta', models.CharField(max_length=100)),
                ('idade_do_atleta', models.IntegerField()),
                ('peso_do_atleta', models.FloatField()),
                ('altura_do_atleta', models.FloatField()),
            ],
        ),
    ]
