# Generated by Django 4.0.6 on 2022-07-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova_competicao', '0003_remove_competicao_nome_da_competicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='competicao',
            name='metros_de_distancia',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='competicao',
            name='tempo_de_chegada_na_primeira_prova',
            field=models.FloatField(default=None),
        ),
    ]
