# Generated by Django 4.0.6 on 2022-07-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova_competicao', '0004_competicao_metros_de_distancia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competicao',
            name='data_e_hora',
        ),
        migrations.AddField(
            model_name='competicao',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competicao',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
