# Generated by Django 4.0.6 on 2022-07-18 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova_competicao', '0005_remove_competicao_data_e_hora_competicao_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competicao',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='competicao',
            name='hora',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
